/*
*  Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
*
*  WSO2 Inc. licenses this file to you under the Apache License,
*  Version 2.0 (the "License"); you may not use this file except
*  in compliance with the License.
*  You may obtain a copy of the License at
*
*    http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*/

@Library('wso2-jenkins-shared-lib')
import org.wso2.util.Constants

//Nodes
def NODE_MASTER = "master"
node(NODE_MASTER) {
    def PRODUCT = "${params.PRODUCT}"
    def VERSION = "${params.VERSION}"
    def REVISION = "${params.REVISION}"
    def ENVIRONMENT = "${params.ENVIRONMENT}"
    //Stacks
    def STACK_NETWORK = "network"
    //Constants
    def DB_CREDS = 'db_creds'
    def GITHUB_CREDS = 'github_creds'
    def BRANCH = '*/master'
    //Return Keys
    def TEST_ENDPOINT_KEY = "HttpURL"
    //Config Files
    def ENV = '/home/jenkins/jenkins_env'
    def PROPERTY_FILE = '/home/jenkins/build.properties'
    //Directories
    def DEPLOYMENT_DIR = "deployment"

    try {
        stage(Constants.Stages.SETUP_ENV) {
            log.info "Load Environment Variables"
            file = load ENV
            env.REGION = getAvailabilityZone()
            cloneRepoToDir ([repoUrl    :"${env.GIT_REPO_CF}",
                             directory  :"${DEPLOYMENT_DIR}",
                             branch     :"${BRANCH}",
                             credID     :"${GITHUB_CREDS}"])
            def props = readProperties file: PROPERTY_FILE
            env.IMAGE_ID = props["${REVISION}"]

        }

        stage(Constants.Stages.ROLLBACK) {
            log.info "Rollback {ENVIRONMENT} environment to revision ${REVISION}"
            if (ENVIRONMENT == "prod") {
                CF = "${WORKSPACE}/${DEPLOYMENT_DIR}/${PRODUCT}/${env.DeploymentPattern}/cf.yaml"
                STACK_NAME = "prod"
            } else if (ENVIRONMENT == "staging") {
                CF = "${WORKSPACE}/${DEPLOYMENT_DIR}/${PRODUCT}/${env.DeploymentPattern}/cf-staging.yaml"
                STACK_NAME = "staging"
            } else {
                CF = "${WORKSPACE}/${DEPLOYMENT_DIR}/${PRODUCT}/${env.DeploymentPattern}/cf-dev.yaml"
                STACK_NAME = "dev"
            }
            deployAWS([wso2InstanceType: "${env.WSO2InstanceType}",
                       product         : "${PRODUCT}",
                       version         : "${VERSION}",
                       keyPairName     : "${env.KeyPairName}",
                       certName        : "${env.CertificateName}",
                       dbCredID        : "${DB_CREDS}",
                       dbType          : "${env.DBType}",
                       amiID           : "${env.IMAGE_ID}",
                       iamRole         : "${env.IAMRole}",
                       region          : "${env.REGION}",
                       stackName       : "${STACK_NAME}",
                       cf              : "${CF}",
                       testEndpoint    : "${TEST_ENDPOINT_KEY}",
                       environment     : "${ENVIRONMENT}",
                       networkStackName: "${STACK_NETWORK}"])
        }

    } catch (exc) {
        log.err "Caught: ${exc}"
        String recipient = env.Email
        mail subject: "${env.JOB_NAME} (${env.BUILD_NUMBER}) build failed",
                body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} failed in Jenkins. Check console output at $BUILD_URL to view the results.",
                to: recipient,
                replyTo: recipient,
                from: 'noreply@wso2cicd.com'
        throw exc
    }

}
